### ISSUE TITLE
Error in initialUserMessage() and storage missing

### ISSUE THREAD

**Issue by TabeaSpahn** [gratifychat/BotMock#4]
1. You messed up the initialUserMessage() method in line 146 of BotMock, so it does not work with actual regular expressions. You take a RegEx, convert it into a String and then convert it back to a RegEx. So if I use a RegEx: /someRegEx/ it is converted to /\/someRegEx\//i.
   So I solved it like this: 
   
   ```
       let p = obj.pattern;
   
       if (Array.isArray(obj.pattern)) {
           for (let i = 0;i < p.length;i++) {
               if ((message.text || message).match(new RegExp(p[i], 'i'))) {
                   message.match = (message.text || message).match(p);
   
                   return (message.text || message).match(new RegExp(p[i], 'i'));
               }
           }
       } else {
           if ((message.text || message).match(new RegExp(p, 'i'))) {
               message.match = (message.text || message).match(new RegExp(p, 'i'))
           }
       }
   
       return (message.text || message).match(new RegExp(p, 'i'));
   ```
2. BotMock.js does not support simple_storage:
   If you want to support that just add the simple_storage.js to your requirements, then you only have to add:
   
   ```
       memory_store: {
           users: {
   
           },
           channels: {
   
           },
           teams: {
   
           },
       }
   ```
   
   to line 11:
   line 11: 
   
   ```
       this.botkit = {
           tasks: [],
           log: function(){}
       };
   ```
   
   Additionally, if you want to access the storage with your Bot you have to add the team_id or user_id to the call back:
   See this example:
   add  
   
   ```
       this.convo.sourceMessage.username = message.username;
   ```
   
   to
   
   ```
       this.convo.sourceMessage.user = message.user;
       this.convo.sourceMessage.channel = message.user;
   ```
   
   in line line 77, 78

and 
to line 245

```
        channel: this.sourceMessage.channel
```

add:

```
        user: this.sourceMessage.username
```

**Comment by amplicity** [comment]
Thank you. Looking into this and making changes to BotMock master where we agree. Will close this issue when master is updated.

**Comment by amplicity** [comment]
@TabeaSpahn 

1:  We agree, merged here - https://github.com/amplicity/BotMock/commit/7d04e0e1120a1c24306e4ff2b56a4a37a6bb5dc5

2. Please submit a PR and we will merge

**Comment by nsbingham** [comment]
@amplicity I'm working on tests that will involve simple_storage. I was just curious why you didn't address item #2 in @TabeaSpahn's issue. Is there another way to approach testing with storage?

**Comment by amplicity** [comment]
We

**Comment by nsbingham** [comment]
@amplicity thanks!

**Comment by ihorrusi** [comment]
@nsbingham see https://github.com/gratifychat/BotMock/commit/2a24d012619d83ea0b52ca78c5f1d913537a35ef
