### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by byt3smith** [gratifychat/BotMock#6]
Would be nice if it was submitted to NPM so it could be properly versioned, auto-udpated as a dependency, simpler installation, etc. 😸

**Comment by amplicity** [comment]
Agreed.

@byt3smith Is the easiest way to submit to npm, [here](https://docs.npmjs.com/getting-started/publishing-npm-packages)?

**Comment by byt3smith** [comment]
Sure is. 💯

**Comment by ihorrusi** [comment]
@byt3smith  npm install --save botkit-mock
